
name: Deploy Medusa Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image
        run: |
          docker build -t medusa-backend .
          docker tag medusa-backend:latest ${{ steps.login-ecr.outputs.registry }}/medusa-backend:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/medusa-backend:latest

      - name: Deploy ECS service
        run: |
          aws ecs update-service             --cluster medusa-cluster             --service medusa-service             --force-new-deployment
